def get_analytics_data():
    return {
        "user_role": "finance",

        "filters": {
            "default_depth_months": 6,
            "max_depth_years": 3,
            "years": [2024, 2025, 2026],
            "selected_year": 2026,
            "contracts": [
                "OE-EE-1-2022/1",
                "OE-EE-2-2023/4",
            ],
            "tko_points": [
                {
                    "eic": "62Z1234567890001",
                    "address": "м. Київ, вул. Прикладна, 1",
                    "osr": "ДТЕК Київські електромережі",
                    "region": "Київ",
                    "note": "Основний офіс",
                },
                {
                    "eic": "62Z1234567890002",
                    "address": "м. Київ, вул. Прикладна, 2",
                    "osr": "ДТЕК Київські електромережі",
                    "region": "Київ",
                    "note": "Склад",
                },
                {
                    "eic": "62Z1234567890003",
                    "address": "м. Львів, вул. Енергетична, 10",
                    "osr": "Львівобленерго",
                    "region": "Львів",
                    "note": "АЗС",
                },
                {
                    "eic": "62Z1234567890004",
                    "address": "м. Одеса, вул. Морська, 5",
                    "osr": "ДТЕК Одеські електромережі",
                    "region": "Одеса",
                    "note": "Резервний об'єкт",
                },
                {
                    "eic": "62Z1234567890005",
                    "address": "м. Дніпро, просп. Енергії, 14",
                    "osr": "ДТЕК Дніпровські електромережі",
                    "region": "Дніпро",
                    "note": "Виробнича точка",
                },
            ],
        },

        "summary": {
            "period_consumption": 52480,
            "period_cost": 263420,
            "average_price": 5.02,
            "ordered_consumption": 56000,
            "actual_consumption": 52480,
            "imbalance": -3520,
            "imbalance_percent": -6.29,
            "forecast_next_month_kwh": 11200,
            "forecast_next_month_cost": 56560,
        },

        "monthly_dynamics": [
            {
                "month": "Січ",
                "actual_kwh": 7600,
                "planned_kwh": 8000,
                "cost_uah": 37400,
                "planned_cost_uah": 39200,
                "avg_price": 4.92,
                "is_forecast": False,
            },
            {
                "month": "Лют",
                "actual_kwh": 8100,
                "planned_kwh": 8400,
                "cost_uah": 40800,
                "planned_cost_uah": 42300,
                "avg_price": 5.04,
                "is_forecast": False,
            },
            {
                "month": "Бер",
                "actual_kwh": 7900,
                "planned_kwh": 7600,
                "cost_uah": 39100,
                "planned_cost_uah": 37600,
                "avg_price": 4.95,
                "is_forecast": False,
            },
            {
                "month": "Кві",
                "actual_kwh": 8800,
                "planned_kwh": 9000,
                "cost_uah": 44900,
                "planned_cost_uah": 45900,
                "avg_price": 5.10,
                "is_forecast": False,
            },
            {
                "month": "Тра",
                "actual_kwh": 9660,
                "planned_kwh": 10400,
                "cost_uah": 48720,
                "planned_cost_uah": 52420,
                "avg_price": 5.04,
                "is_forecast": False,
            },
            {
                "month": "Чер",
                "actual_kwh": 10420,
                "planned_kwh": 12600,
                "cost_uah": 52500,
                "planned_cost_uah": 63500,
                "avg_price": 5.04,
                "is_forecast": False,
            },
            {
                "month": "Лип прогноз",
                "actual_kwh": None,
                "planned_kwh": 11200,
                "cost_uah": None,
                "planned_cost_uah": 56560,
                "avg_price": 5.05,
                "is_forecast": True,
            },
        ],

        "year_over_year": [
            {
                "month": "Січ",
                "current_year_kwh": 7600,
                "previous_year_kwh": 7100,
                "current_year_cost": 37400,
                "previous_year_cost": 33100,
            },
            {
                "month": "Лют",
                "current_year_kwh": 8100,
                "previous_year_kwh": 7800,
                "current_year_cost": 40800,
                "previous_year_cost": 36200,
            },
            {
                "month": "Бер",
                "current_year_kwh": 7900,
                "previous_year_kwh": 8200,
                "current_year_cost": 39100,
                "previous_year_cost": 37800,
            },
            {
                "month": "Кві",
                "current_year_kwh": 8800,
                "previous_year_kwh": 8400,
                "current_year_cost": 44900,
                "previous_year_cost": 39200,
            },
            {
                "month": "Тра",
                "current_year_kwh": 9660,
                "previous_year_kwh": 9100,
                "current_year_cost": 48720,
                "previous_year_cost": 42600,
            },
            {
                "month": "Чер",
                "current_year_kwh": 10420,
                "previous_year_kwh": 9600,
                "current_year_cost": 52500,
                "previous_year_cost": 45100,
            },
        ],

        "imbalances": [
            {"month": "Січ", "ordered_kwh": 8000, "actual_kwh": 7600, "imbalance_kwh": -400},
            {"month": "Лют", "ordered_kwh": 8400, "actual_kwh": 8100, "imbalance_kwh": -300},
            {"month": "Бер", "ordered_kwh": 7600, "actual_kwh": 7900, "imbalance_kwh": 300},
            {"month": "Кві", "ordered_kwh": 9000, "actual_kwh": 8800, "imbalance_kwh": -200},
            {"month": "Тра", "ordered_kwh": 10400, "actual_kwh": 9660, "imbalance_kwh": -740},
            {"month": "Чер", "ordered_kwh": 12600, "actual_kwh": 10420, "imbalance_kwh": -2180},
        ],

        "insights": [
            {
                "title": "Найбільше відхилення",
                "value": "Червень",
                "description": "-2 180 кВт·год від замовленого обсягу",
                "status": "warning",
            },
            {
                "title": "Пік споживання",
                "value": "10 420 кВт·год",
                "description": "Найвище споживання у червні",
                "status": "success",
            },
            {
                "title": "Прогноз липня",
                "value": "11 200 кВт·год",
                "description": "Плановий орієнтир на наступний місяць",
                "status": "neutral",
            },
        ],
    }