def get_documents_data():
    return {
        "summary": {
            "total": 6,
            "waiting_signature": 3,
            "urgent": 1,
            "signed": 2,
        },
        "documents": [
            {
                "number": "DOC-2026-001",
                "title": "Договір постачання електричної енергії",
                "type": "Договір",
                "contract": "OE-EE-1-2022/1",
                "created_at": "01.06.2026",
                "sign_until": "15.06.2026",
                "status": "waiting",
                "status_text": "Очікує підпису",
                "pdf_url": "/static/docs/sample.pdf",
                "note": "Потрібно скачати, роздрукувати, підписати та передати постачальнику.",
            },
            {
                "number": "DOC-2026-002",
                "title": "Додаткова угода щодо зміни реквізитів",
                "type": "Додаткова угода",
                "contract": "OE-EE-1-2022/1",
                "created_at": "03.06.2026",
                "sign_until": "10.06.2026",
                "status": "urgent",
                "status_text": "Терміново",
                "pdf_url": "/static/docs/sample.pdf",
                "note": "Термін підписання наближається.",
            },
            {
                "number": "DOC-2026-003",
                "title": "Додаток з переліком ТКО",
                "type": "Додаток",
                "contract": "OE-EE-2-2023/4",
                "created_at": "05.06.2026",
                "sign_until": "20.06.2026",
                "status": "waiting",
                "status_text": "Очікує підпису",
                "pdf_url": "/static/docs/sample.pdf",
                "note": "Містить актуальний перелік точок комерційного обліку.",
            },
            {
                "number": "DOC-2026-004",
                "title": "Додаткова угода щодо договірних величин",
                "type": "Додаткова угода",
                "contract": "OE-EE-2-2023/4",
                "created_at": "28.05.2026",
                "sign_until": "08.06.2026",
                "status": "waiting",
                "status_text": "Очікує підпису",
                "pdf_url": "/static/docs/sample.pdf",
                "note": "Потребує підписання обома сторонами.",
            },
            {
                "number": "DOC-2026-005",
                "title": "Акт погодження комерційних умов",
                "type": "Додаток",
                "contract": "OE-EE-1-2022/1",
                "created_at": "12.05.2026",
                "sign_until": "25.05.2026",
                "status": "signed",
                "status_text": "Підписано",
                "pdf_url": "/static/docs/sample.pdf",
                "note": "Документ підписано клієнтом.",
            },
            {
                "number": "DOC-2026-006",
                "title": "Додаток щодо порядку обміну документами",
                "type": "Додаток",
                "contract": "OE-EE-3-2024/2",
                "created_at": "10.05.2026",
                "sign_until": "20.05.2026",
                "status": "signed",
                "status_text": "Підписано",
                "pdf_url": "/static/docs/sample.pdf",
                "note": "Документ підписано клієнтом.",
            },
        ],
    }