def get_invoices_data():
    return {
        "invoice_periods": [
            {
                "period": "Липень 2026",
                "has_actual": False,
                "advance_invoices": [
                    {
                        "number": "АВ-2026-071",
                        "subject": "Споживання е/е",
                        "type": "Аванс",
                        "contract": "OE-EE-1-2022/1",
                        "due_date": "05.07.2026",
                        "amount": 18000,
                        "paid": False,
                        "overdue": False,
                        "is_new": True,
                        "pdf_url": "#",

                        "document_date": "01.07.2026",
                        "advance_percent": 60,
                        "sap_number": "5100002071",
                        "supplier_bank_account": "UA123456789012345678901234567",
                        "payment_purpose": "Авансова оплата за електричну енергію згідно рахунку АВ-2026-071",
                        "total_without_vat": 15000,
                        "vat_rate": 20,
                        "vat_amount": 3000,
                        "includes_distribution": False,

                        "payments": [],

                        "calculation_items": [
                            {
                                "position_number": "001",
                                "name": "Електроенергія",
                                "dso": "ДТЕК Київські електромережі",
                                "quantity": 1,
                                "price": 15000,
                                "amount": 15000,
                                "details_by_tko": [],
                            },
                        ],
                    },
                    {
                        "number": "АВ-2026-072",
                        "subject": "Споживання е/е",
                        "type": "Аванс",
                        "contract": "OE-EE-1-2022/1",
                        "due_date": "15.07.2026",
                        "amount": 12000,
                        "paid": True,
                        "overdue": False,
                        "is_new": True,
                        "pdf_url": "#",

                        "document_date": "10.07.2026",
                        "advance_percent": 40,
                        "sap_number": "5100002072",
                        "supplier_bank_account": "UA123456789012345678901234567",
                        "payment_purpose": "Авансова оплата за електричну енергію згідно рахунку АВ-2026-072",
                        "total_without_vat": 10000,
                        "vat_rate": 20,
                        "vat_amount": 2000,
                        "includes_distribution": False,

                        "payments": [
                            {
                                "number": "PAY-2026-0001",
                                "payment_date": "18.07.2026",
                                "total_amount": 50000,
                                "invoice_amount": 12000,
                            },
                        ],

                        "calculation_items": [
                            {
                                "position_number": "001",
                                "name": "Електроенергія",
                                "dso": "ДТЕК Київські електромережі",
                                "quantity": 1,
                                "price": 10000,
                                "amount": 10000,
                                "details_by_tko": [],
                            },
                        ],
                    },
                ],
            },
            {
                "period": "Червень 2026",
                "has_actual": True,
                "actual_invoice": {
                    "number": "ФАКТ-2026-061",
                    "subject": "Споживання е/е",
                    "type": "За фактичне споживання",
                    "contract": "OE-EE-1-2022/1",
                    "due_date": "20.06.2026",
                    "amount": 42300,
                    "paid": False,
                    "overdue": True,
                    "is_new": False,
                    "pdf_url": "#",

                    "document_date": "30.06.2026",
                    "sap_number": "5100002061",
                    "act_number": "АКТ-2026-061",
                    "supplier_bank_account": "UA123456789012345678901234567",
                    "payment_purpose": "Оплата за електричну енергію згідно рахунку ФАКТ-2026-061",
                    "total_without_vat": 35250,
                    "vat_rate": 20,
                    "vat_amount": 7050,
                    "includes_distribution": True,

                    "payments": [
                        {
                            "number": "PAY-2026-0003",
                            "payment_date": "25.06.2026",
                            "total_amount": 20000,
                            "invoice_amount": 15000,
                        },
                        {
                            "number": "PAY-2026-0004",
                            "payment_date": "27.06.2026",
                            "total_amount": 10000,
                            "invoice_amount": 5000,
                        },
                    ],

                    "calculation_items": [
                        {
                            "position_number": "001",
                            "name": "Електроенергія",
                            "dso": "ДТЕК Київські електромережі",
                            "quantity": 5000,
                            "price": 4.4422,
                            "amount": 22211.00,
                            "details_by_tko": [
                                {
                                    "eic": "62Z1234567890001",
                                    "address": "м. Київ, вул. Прикладна, 1",
                                    "payment_type": "Електроенергія",
                                    "quantity": 5000,
                                    "price": 3.2000,
                                    "amount": 16000.00,
                                },
                                {
                                    "eic": "62Z1234567890001",
                                    "address": "м. Київ, вул. Прикладна, 1",
                                    "payment_type": "Маржа",
                                    "quantity": 5000,
                                    "price": 0.1500,
                                    "amount": 750.00,
                                },
                                {
                                    "eic": "62Z1234567890001",
                                    "address": "м. Київ, вул. Прикладна, 1",
                                    "payment_type": "Розподіл",
                                    "quantity": 5000,
                                    "price": 1.0922,
                                    "amount": 5461.00,
                                },
                            ],
                        },
                        {
                            "position_number": "002",
                            "name": "Електроенергія",
                            "dso": "ДТЕК Київські електромережі",
                            "quantity": 3420,
                            "price": 3.8126,
                            "amount": 13039.00,
                            "details_by_tko": [
                                {
                                    "eic": "62Z1234567890002",
                                    "address": "м. Київ, вул. Прикладна, 2",
                                    "payment_type": "Електроенергія",
                                    "quantity": 3420,
                                    "price": 3.1000,
                                    "amount": 10602.00,
                                },
                                {
                                    "eic": "62Z1234567890002",
                                    "address": "м. Київ, вул. Прикладна, 2",
                                    "payment_type": "Маржа",
                                    "quantity": 3420,
                                    "price": 0.1200,
                                    "amount": 410.40,
                                },
                                {
                                    "eic": "62Z1234567890002",
                                    "address": "м. Київ, вул. Прикладна, 2",
                                    "payment_type": "Розподіл",
                                    "quantity": 3420,
                                    "price": 0.5926,
                                    "amount": 2026.60,
                                },
                            ],
                        },
                    ],

                    "details": {
                        "actual_amount": 42300,
                        "advance_paid_total": 37000,
                        "opening_balance": -12500,
                        "result": -7200,
                        "result_text": "Переплата переноситься на аванси майбутніх періодів.",
                        "linked_advances": [
                            {
                                "number": "АВ-2026-061",
                                "advance_percent": 30,
                                "amount": 12000,
                                "paid_amount": 12000,
                                "pdf_url": "#",
                            },
                            {
                                "number": "АВ-2026-062",
                                "advance_percent": 40,
                                "amount": 15000,
                                "paid_amount": 15000,
                                "pdf_url": "#",
                            },
                            {
                                "number": "АВ-2026-063",
                                "advance_percent": 30,
                                "amount": 10000,
                                "paid_amount": 10000,
                                "pdf_url": "#",
                            },
                        ],
                    },
                },
            },
        ],
        "acts": [
            {
                "subject": "Споживання е/е",
                "number": "АКТ-2026-061",
                "contract": "OE-EE-1-2022/1",
                "period": "Червень 2026",
                "act_date": "30.06.2026",
                "quantity": 8420,
                "amount": 42300,
                "is_new": False,
                "pdf_url": "#",
            },
        ],
    }